version: "3"

services:
  trojan:
    image: teddysun/trojan-go
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./trojan/config:/etc/trojan-go
      - ./ssl:/ssl
    depends_on:
      - caddy

  caddy:
    image: caddy
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./wwwroot:/usr/src
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory
